[package]
name = "proof-stack-game-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui_extras = { version = "0.30.0", features = ["image"] }
lib = { path = "../lib" }
mathjax_svg = "3.1.2"
memoize = "0.4.2"
resvg = "0.44.0"
